### ISSUE TITLE
npm install error with the latest typescript and the latest angular2-apollo

### ISSUE THREAD

**Issue by bkinsey808** [apollostack/angular2-apollo#106]
npm ERR! Linux 4.2.0-41-generic
npm ERR! argv "/home/bkinsey/.nvm/versions/node/v6.3.1/bin/node" "/home/bkinsey/.nvm/versions/node/v6.3.1/bin/npm" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-apollo@0.4.6 build: `tsc`
npm ERR! Exit status 2

**Comment by kamilkisiela** [comment]
#108
