### ISSUE TITLE
Not working with Angular Universal

### ISSUE THREAD

**Issue by mmgdort** [apollostack/angular2-apollo#116]
I'm using Universal-Starter. When the app is running in the client all is fine. When it runs on the server the following error is thrown in the apollo-client package.

```shell
 'Network error: fetch is not defined'
```

**Comment by kamilkisiela** [comment]
Try to install `isomorphic-fetch` or some similar polyfill of `fetch`

**Comment by kamilkisiela** [comment]
You of course have to have `Promise` available. NodeJS 6+ (or maybe 5+ too) supports Promises, but if not, try to install polyfill of `Promise`, like `es6-promise` for example.

**Comment by kamilkisiela** [comment]
I'm going to update this https://github.com/kamilkisiela/universal-starter-apollo
It's a Universal Starter but with ApolloStack. 

Maybe you want to help me?

**Comment by mmgdort** [comment]
Ok, I'll take a look, don't know if I'll be able to do it

**Comment by mmgdort** [comment]
I'm not having lucky.
I've installed isomorphic-fetch and imported in server.ts but it throws to me another error

```
Network error: only absolute urls are supported
```

**Comment by kamilkisiela** [comment]
Take a look at this (I updated Angular to v2.0.0)
https://github.com/kamilkisiela/universal-starter-apollo

**Comment by mmgdort** [comment]
Now it works great!

I was creating the network interface like this
```
const networkInterface = createNetworkInterface('http://localhost:3000');
```
without the ```/graph``` path because I understood that when I read the docs 
http://dev.apollodata.com/angular2/initialization.html#creating-client

Which says 
``` javascript
// by default, this client will send queries to `/graphql` (relative to the URL of your app)
const client = new ApolloClient({
  networkInterface: createNetworkInterface('http://my-api.grapql.com'),
});
```

Thanks a lot !

**Comment by ngocdiep** [comment]
I'm using angular 4, and this issue happens (Error: Network error: fetch is not defined).
Could you help me how to fix it?

Best thanks!!
