### ISSUE TITLE
Build failing with apollo-client > 0.4.15

### ISSUE THREAD

**Issue by stubailo** [apollostack/angular2-apollo#122]
@kamilkisiela @Urigo any reason why? I see we have just been closing the greenkeeper PRs.

**Comment by kamilkisiela** [comment]
It breaks on `0.4.20`.

@stubailo Could you explain what this stands for?

```
Can't find field allHeroes on object (ROOT_QUERY) {}. Perhaps you want to use the `returnPartialData` option?
```

**Comment by kamilkisiela** [comment]
It works with `returnPartialData: true` but why? Changelog [says](https://github.com/apollostack/apollo-client/blob/master/CHANGELOG.md#v0420)  nothing about it.

**Comment by kamilkisiela** [comment]
And I think the `Promise` should resolve when the whole data is ready soooo... I'm waiting to merge #123 until you'll give some light on the topic.
