### ISSUE TITLE
Remove Apollo decorator

### ISSUE THREAD

**Issue by kamilkisiela** [apollostack/angular2-apollo#125]
It's deprecated since `v0.5.0`

**Comment by kamilkisiela** [comment]
@Urigo Not quite sure if we should push it with `v0.6.0` or with `v1.0.0`.

**Comment by Urigo** [comment]
`0.6.0`

**Comment by Urigo** [comment]
@kamilkisiela can you link to the issue (or create one) on the Angular repo to explain why we decided not to use it for now?

**Comment by kamilkisiela** [comment]
@Urigo Sure!

**Comment by Urigo** [comment]
keep track here - https://github.com/apollostack/angular2-apollo/issues/155
