### ISSUE TITLE
Angular 2 Release Candidate 1

### ISSUE THREAD

**Issue by TobiasKrogh** [apollostack/angular2-apollo#14]
Hi,

any chance angular2-apollo gets updated to work with the Angular 2 RC1?

Cheers

**Comment by kamilkisiela** [comment]
@TobiasKrogh  I think I'm going to work on it in the next week :)

**Comment by ansarizafar** [comment]
@kamilkisiela any update?

**Comment by kamilkisiela** [comment]
Could you guys check [this PR](https://github.com/apollostack/angular2-apollo/pull/16)?
Is this working for you?

I will try to update also the ApolloClient.

**Comment by kamilkisiela** [comment]
#17 Should fix it

**Comment by Urigo** [comment]
published 0.1.0, thanks @kamilkisiela !
