### ISSUE TITLE
Options typings for Angular2Apollo service

### ISSUE THREAD

**Issue by Crevil** [apollostack/angular2-apollo#141]
To help development, typings on the `options` arguments in `Angular2Apollo` service methods could be added.

### `Angular2Apollo.watchQuery()`
Link to source: [`Angular2Apollo.watchQuery()`](https://github.com/apollostack/angular2-apollo/blob/845a6b68d1b2dbf8f0ee577206007323cd8d38d1/src/Angular2Apollo.ts#L24)
Typedef: [`DeprecatedWatchQueryOptions`](https://github.com/apollostack/apollo-client/blob/18b803c4c6096be5f9470058d2176445bb9faa81/src/core/watchQueryOptions.ts#L69)

### `Angular2Apollo.query()`
Link to source: [`Angular2Apollo.query()`](https://github.com/apollostack/angular2-apollo/blob/845a6b68d1b2dbf8f0ee577206007323cd8d38d1/src/Angular2Apollo.ts#L28)
Typedef: [`DeprecatedWatchQueryOptions`](https://github.com/apollostack/apollo-client/blob/18b803c4c6096be5f9470058d2176445bb9faa81/src/core/watchQueryOptions.ts#L69)

### `Angular2Apollo.mutate()`
Link to source: [`Angular2Apollo.mutate()`](https://github.com/apollostack/angular2-apollo/blob/845a6b68d1b2dbf8f0ee577206007323cd8d38d1/src/Angular2Apollo.ts#L32)
Typedef: [`ApolloClient.mutate()`](https://github.com/apollostack/apollo-client/blob/18b803c4c6096be5f9470058d2176445bb9faa81/src/ApolloClient.ts#L332)

### `Angular2Apollo.subscribe()`
Link to source: [`Angular2Apollo.subscribe()`](https://github.com/apollostack/angular2-apollo/blob/845a6b68d1b2dbf8f0ee577206007323cd8d38d1/src/Angular2Apollo.ts#L36)
Typedef: [`DeprecatedSubscriptionOptions `](https://github.com/apollostack/apollo-client/blob/18b803c4c6096be5f9470058d2176445bb9faa81/src/core/watchQueryOptions.ts#L98)

**Comment by kamilkisiela** [comment]
@Crevil Totally agree we need those.

Imagine the situation when the ApolloClient changes those interfaces. 

Let's say we support `apollo-client` in versions `^0.5.0`. 
Now when there's a change in those interfaces we have to release a new version that supports only `^0.5.2`.

I see three ways of doing this:

- release new versions of `angular2-apollo` on each change
- make `apollo-client` expose to those those interfaces
- create our own, internal interfaces in `angular2-apollo`

Which would be the best in your opinion?

**Comment by Crevil** [comment]
@kamilkisiela 
The first option is the most tedious one but keeps things synchronized closely. 
The second one would be an easy fix and would work as long as the service is a simple wrapper.
The last one makes things confusing as long as we are only delegating things to `apollo-client` as they are the same interfaces. 

From this I think option two is the better one, for now. If the service get to be more than a wrapper at some point, this could be rethought.

**Comment by kamilkisiela** [comment]
#145

**Comment by kamilkisiela** [comment]
#145
