### ISSUE TITLE
Typescript error using RxJs

### ISSUE THREAD

**Issue by baloodevil** [apollostack/angular2-apollo#180]
The Apollo Angular 2 RxJs [example code ](http://dev.apollodata.com/angular2/queries.html#rxjs)gives a Typescript error (but not a runtime error) for the following line...
```JavaScript
 this.data = this.apollo.watchQuery({ query: FeedQuery })
        .map(({data}) => data.feed);
    }
```

```
[ts] Type 'Observable<any>' is not assignable to type 'ApolloQueryObservable<any>'.
       Property 'apollo' is missing in type 'Observable<any>'.
```
The return type of watchQuery is `ApolloQueryObservable<any>`.  The type of the class property `data` is too. ?

**Comment by baloodevil** [comment]
This is not an issue.  I misunderstood what the method chain was returning.  It is of type Observable<any> rather than ApolloQueryObservable<any>, because of the .map function.

**Comment by jjenzz** [comment]
I have just raised a similar issue here https://github.com/apollographql/angular-docs/issues/64

Unfortunately, switching the `users$` type to `Observable<any>` does not fix the issue for me. Does anyone have a working solution for this?
