### ISSUE TITLE
Query sent multiple times when binding to more than one async pipe

### ISSUE THREAD

**Issue by glendaviesnz** [apollostack/angular2-apollo#181]
Hi

If I bind a .watchQuery result to multiple async pipes in a single view, then for each binding a new query is sent to the server. 

It appears that each subscription to a given ApolloQueryObservable causes the query to be sent to the server,  as multiple subscriptions to the  observable returned by .watchQuery within a component class also initiates the call to the server for each new subscription. 

It seems as though the underlying sequence needs something like an rx .shareReplay() adding, or maybe I am doing something wrong? I am just running a simple

    this.meetings = this.apollo.watchQuery({
            query: meetingsQuery,
            notifyOnNetworkStatusChange: true,
            variables: {
                site: 'gdavies',
                meetingGroup: 'Board'
            }
        })

Should I be able to bind the this.meetings to mulitple async pipes in the view and only have the query execute once against the server?

Thanks
Glen

**Comment by kamilkisiela** [comment]
Hi Glen!

`Angular2Apollo` service works exactly the same as `Http` service. It means that if you use `AsyncPipe` multiple times it makes multiple requests. To avoid it you can wrap it manually with an operator of RxJS to share the Observable.

**Comment by glendaviesnz** [comment]
ok - thanks for clarifying that it is expected behaviour - as you note, can deal with it by manually wrapping if needed.

**Comment by mluis** [comment]
I believe I'm having the same issue.

The `.valueChanges.subscribe(callback)` seems to be firing `callback` multiple times.
How do you solved this?
