### ISSUE TITLE
Confusing import statement

### ISSUE THREAD

**Issue by swarthout** [apollostack/angular2-apollo#2]
First of all, great work with this initial draft of the apollo client! I look forward to using it as it matures. I started reading through the code today and I thought this import on the example page was a little confusing:
import {ApolloQueryPipe, APOLLO_ANGULAR2_PROVIDERS, ApolloAngular2} from "angular2-apollo";
It seems like APOLLO_ANGULAR2_PROVIDERS is being imported but not used, could you explain this to me or put in the README or the guide why it is important? I can see myself leaving it out if it is necessary. Also, I feel like the naming of ApolloAngular2 is a bit of a misnomer considering the package name is a slight inversion (ApolloAngular2 vs angular2-apollo). I think making these consistent by changing the import name or the package to apollo-angular2 would make using this package a little more intuitive.

Thanks and keep up the great work!

**Comment by Urigo** [comment]
@swarthout can you check the readme now and see if it's more understandable?

**Comment by swarthout** [comment]
Excellent! The readme is much clearer now
