### ISSUE TITLE
server-side rendering

### ISSUE THREAD

**Issue by bkinsey808** [apollostack/angular2-apollo#20]
Curious if there are any plans for server side rendering? Was advised to make an issue here.

https://github.com/apollostack/apollo-server/issues/16

**Comment by kamilkisiela** [comment]
@bkinsey808 Here's my implementation of `angular2-apollo` with `angular-universal`.

[kamilkisiela/universal-starter-apollo](https://github.com/kamilkisiela/universal-starter-apollo).

@Urigo  And... it's working! :fire:

**Comment by Urigo** [comment]
OMG!!  @kamilkisiela you are **the** king.

**Comment by kamilkisiela** [comment]
SSR support [has been released](https://github.com/apollostack/angular2-apollo/releases/tag/0.3.0) with the latest version.
