### ISSUE TITLE
Expose apollo-client resetStore() #FeatureRequest

### ISSUE THREAD

**Issue by manuelfink** [apollostack/angular2-apollo#203]
I'm trying to clear the whole apollo cache on logout. However this is a little bit tough since Angular2Apollo neither does pass down function apollo-client.resetStore(), nor the apollo.client is accessible, since it is private.

Would it not make sense to either make apollo.client public or pass down resetStore and every other apollo-client functionality?

**Comment by KeithGillette** [comment]
Is `ApolloClient.resetStore()` indeed supported in Apollo-Angular?

I don't see the method defined in the `Apollo.d.ts` TypeScript and when I attempt to call `Apollo.resetStore()` from Apollo-Angular 0.13.0 I get `Apollo.resetStore is not a function`.

**Comment by kamilkisiela** [comment]
@KeithGillette 

```ts
Apollo.getClient().resetStore();
```

**Comment by Dunos** [comment]
@kamilkisiela I'm trying that code but it get `Property 'getClient' does not exist on type 'typeof Apollo',` where should I import Apollo from, right now Im doing `
import { Apollo } from "apollo-angular";`

**Comment by KeithGillette** [comment]
The following works for me:
``
import { Apollo } from 'apollo-angular';
Apollo.getClient().resetStore();
```

**Comment by Dunos** [comment]
Which version of apollo-angular are you using @KeithGillette ? That code doesn't work for me, I'm on 0.13.0

**Comment by KeithGillette** [comment]
I am using:
```
    "apollo-angular": "0.13.0",
    "apollo-client": "1.1.1",

    "typescript": "2.3.2"
```

Thought I don't think it's relevant to this issue, I also reference custom [Apollo GraphQL Meteor Integration Typings](https://github.com/KeithGillette/Apollo-GraphQL-Meteor-Integration-Typings) in my project's `typings.d.ts`.

**Comment by Dunos** [comment]
I have those versions too but for some reason I still get the error `Property 'getClient' does not exist on type 'typeof Apollo'`
