### ISSUE TITLE
How to run with JiT compilation? [solved]

### ISSUE THREAD

**Issue by aaroncalderon** [apollostack/angular2-apollo#204]
I am working on an application that will use GraphQL and I am using the example from  `anngular2-apollo` as a guide to put it together.

I am trying to iron out a bug wher my `data` variable does not provide the data I expect.

To troublesoot I'm trying to serve the example with JiT so I can debug it with Augury, but I cannot figureout how to disable AoT.

Can anyone point me in the right direction?

Thanks.

**Comment by kamilkisiela** [comment]
1. Compile files with `tsc` (`typescript` package) instead of `ngc` from `@angular/compiler-cli`
1. Use `@angular/platform-browser-dynamic` with `platformBrowserDynamic`

and that's it.

**Comment by aaroncalderon** [comment]
@kamilkisiela So, changing the `package.json` to use `tsc` instead of `ngc`:

```diff
 examples/hello-world/package.json | 11 ++++++++---
 1 file changed, 8 insertions(+), 3 deletions(-)

diff --git a/examples/hello-world/package.json b/examples/hello-world/package.json
index 49bfaca..82009e1 100644
--- a/examples/hello-world/package.json
+++ b/examples/hello-world/package.json
@@ -11,7 +11,10 @@
     "build": "./node_modules/.bin/ngc -p src/tsconfig.aot.json",
     "test": "npm run build",
     "postbuild": "npm run tree-shaking",
-    "tree-shaking": "node_modules/.bin/rollup -c rollup.config.js"
+    "tree-shaking": "node_modules/.bin/rollup -c rollup.config.js",
+    "build:jit": "./node_modules/.bin/tsc -p src/tsconfig.json",
+    "client:jit": "ng serve --proxy-conf proxy.conf.json --port 4200",
+    "start:jit": "concurrently \"npm run server\" \"npm run client:jit\""
   },
   "private": true,
   "dependencies": {

```

Then changing `main.ts` to use `platformBrowserDynamic` 

```diff
 examples/hello-world/src/main.ts | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/examples/hello-world/src/main.ts b/examples/hello-world/src/main.ts
index 41a7a1a..1d91a20 100644
--- a/examples/hello-world/src/main.ts
+++ b/examples/hello-world/src/main.ts
@@ -1,6 +1,6 @@
 import './polyfills';
 
-import { platformBrowser } from '@angular/platform-browser';
-import { AppModuleNgFactory } from './aot/app/app.module.ngfactory';
+import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
+import { AppModule } from './app/app.module';
 
-platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
+platformBrowserDynamic().bootstrapModule(AppModule);

```

I got it. So, I gues we can close this issue.

But, now I am experiencing the same issue I have on my other project.

 I will leave it open for a few days in case anyone can share any thoughts on the below. 

# Issue Background

I am trying to use the `.map()` technique to get the data to my Angular template (same as demostrated on this sample and the [`apollostack/angular2-docs` using with rxjs](https://github.com/apollostack/angular2-docs/blob/master/source/queries.md#using-with-rxjs)), but I can only get the data through the `.subscribe()` technique as demostrated on the [`angular2-docs` basic queries](https://github.com/apollostack/angular2-docs/blob/master/source/queries.md#basic-queries).

I am using graphql on top of `sequelize` and `sequelize-msnodesqlv8` to interact with a MSSQL db.

# troubleshooting with __angular2-apollo__ `hello-world` sample

I was runing the sample code, and I integrated my work with __sequelize__, then...

## With AoT

I ran the sample code with AoT and I was able to querie my MSSQL DB through GraphQL, but I was getting some weird error about NgFor not able to work with [Objects].

## With JiT

The sample app code experiences the same issue as my other project. 

The users variable looks like this:

![image](https://cloud.githubusercontent.com/assets/14810269/21458066/5427d356-c8f9-11e6-940b-e6681f8ecc84.png)

But, the data variable, which is the variable I'm using to get the data from MSSQL with the same code and approas as for users, looks like this:

![image](https://cloud.githubusercontent.com/assets/14810269/21458096/782c5a38-c8f9-11e6-8160-218c4c072588.png)

Notice that the `data.apolo.apollo:observableQueryRef` is empty. Even after several `this.idFilter.next(_id);` calls, it will not querie the DB. Even thoug it was querying the DB when I ran the code on AoT.

If anyone can share any thoughs It would be appreciated.
