### ISSUE TITLE
ApolloQueryObservable not working with rxjs forkJoin #bug

### ISSUE THREAD

**Issue by manuelfink** [apollostack/angular2-apollo#219]
I have the problem that I need to resolve two data sources for a screen and can start rendering screen as soon as both are available. However Observable.forkJoin seem not to be working with Apollo. Is this a bug or am I doing anything wrong?

```
import {Observable, Subject} from "rxjs/Rx";

let fork = Observable.forkJoin(
  this.apollo.watchQuery({query:query})
);
fork.subscribe({
  (data) => console.log(data);
})
```

**Comment by manuelfink** [comment]
I think this is more likely an issue with  apollo-client than angular2-apollo, thus posted in apollo-client. https://github.com/apollostack/apollo-client/issues/1109

**Comment by kamilkisiela** [comment]
It's because an `Observable` from the `watchQuery` method never completes.
The `forkJoin` operator will work with `query` method (`angular2-apollo` since v0.8.0 returns an Observable instead of a Promise).

**Comment by kamilkisiela** [comment]
Also, because of that you cannot use `toPromise` operator on an `Observable` returned by `watchQuery` method.

**Comment by manuelfink** [comment]
@kamilkisiela shouldn't forkJoin work with apollo-client-rxjs https://github.com/apollostack/apollo-client/issues/430?

```
import { rxify, RxApolloClient } from 'apollo-client-rxjs';

let fork = Observable.forkJoin(
  new RxApolloClient( this.apollo.watchQuery({query:query}) ),
  new RxApolloClient( this.route.params.switchMap((params: Params) => this.apollo.watchQuery({query: query2, variables{id: params.id}}) )
);
fork.subscribe(...)
```

this seems not to be working for me?

**Comment by kamilkisiela** [comment]
@manuelfink You define what the `switchMap` operator returns so how it can return `watchQuery` instead of `query`?
