### ISSUE TITLE
use defaultClient in @Apollo Decorator

### ISSUE THREAD

**Issue by Quramy** [apollostack/angular2-apollo#22]
Hi. I'm trying angular2-apollo reading http://docs.apollostack.com/apollo-client/angular2.html#apollo .
I'm confused because the following usage of Apollo decorator:

```ts
@Component({...})
@Injectable()
@Apollo({
  client,
  queries(context) {...}
})
class postsList {
  
}
```

It seems that the `client` parameter is required. Can you make it optional? I want angular2-apollo uses the defaultApolloClient by the default.

**Comment by Urigo** [comment]
@Quramy how would you want to see the API?
also how would the import statements look?

**Comment by Quramy** [comment]
Thanks for your reply.

I see https://github.com/apollostack/angular2-apollo/blob/master/src/angular2Apollo.ts#L14 so it seems that we can use the `apolloClient` provided by `Angular2Apollo` service.

And I also see https://github.com/apollostack/angular2-apollo/blob/master/examples/hello-world/client/main.ts#L35 .
In this code, you set `client` option to `@Apollo` decorator's argument but the `client` isn't provided by the `Angular2Apollo` provider. Why don't you use the client provided by `Angular2Apollo` in `@Apollo` decorator ? Are decorators and providers(DI) incompatible?

**Comment by kamilkisiela** [comment]
We would have to wrap the constructor of a component to have an access to `defaultApolloClient`. I'm going to think about it!

**Comment by kamilkisiela** [comment]
Closing in favor of #41
