### ISSUE TITLE
Update Apollo Client dependency to 0.6

### ISSUE THREAD

**Issue by helfer** [apollostack/angular2-apollo#223]
@kamilkisiela We just updated the typings in apollo-client to use @types/graphql and released it as version 0.6. I think a new major version of angular2-apollo should be released because 0.6 will be incompatible with the current version and its grapqhl typings.

**Comment by kamilkisiela** [comment]
@helfer I will test it and release as `0.9.0-rc.2` soon,

**Comment by kamilkisiela** [comment]
@helfer Done, I will wait for Uri to release it.

I really like the communication from past two days! All the changes goes smooooth
