### ISSUE TITLE
Should the decorator use metadata?

### ISSUE THREAD

**Issue by bkinsey808** [apollostack/angular2-apollo#26]
One of the angular2 core devs mentioned in a slack that it was not recommended practice (in typescript) to have decorators that set methods or properties on the class. Instead, in angular2, decorators set metadata. Could the decorator in this project be re-written to use metadata somehow for the mutation methods instead of directly setting a method?

**Comment by Urigo** [comment]
@bkinsey808 can you please send some links and info where I can read more about it?
also maybe how would you see the new implementation?
Thanks

**Comment by bkinsey808** [comment]
I wish I had saved the slack discussion on angularbuddies in the typescript channel where I asked about this. I can't find it now. @robwormald was the angular core dev I slacked with who gave me his opinion about decorator best practice.

What I'm visualizing is that instead of having the decorator set things directly on the component, instead metadata is set. A service is injected into the component that will allow the component to consume both queries and mutations via that metadata. I *think* this will make it easier to type check. 

I think this issue relates somewhat to this issue: https://github.com/apollostack/apollo-server/issues/17

Maybe we should wait for that above issue to get resolved before tackling this one?

**Comment by kamilkisiela** [comment]
@bkinsey808 But how that service would know about the component? You can't read metadata without providing a target class.

We could inject that service (let's call it ApolloHandler) inside Apollo decorator using this:

```js
Reflect.defineMetadata('parameters', [[new InjectMetadata(ApolloHandler)]], target);
```

But how read metadata inside ApolloHandler:

```js
Reflect.getMetadata('parameters'); // target?
```

ApolloHandler could receive an instance of component as an argument of some class or just inside constructor but it's not too user-friendly, I think.

**Comment by kamilkisiela** [comment]
Closing in favor of #41
