### ISSUE TITLE
Invalid provider error (RC3)

### ISSUE THREAD

**Issue by TrikinCurt** [apollostack/angular2-apollo#32]
Unsure if this is specific to Angular2 rc3, but I am getting an error:

Invalid provider - only instances of Provider and Type are allowed, got: [object Object]

This is using Webpack for what it is worth, but the code DID work in the past.  The error is when bootstrapping the Apollo Client.

**Comment by kamilkisiela** [comment]
Is this how you boostrap your app?

```js
import { bootstrap } from '@angular/core';
import { APOLLO_PROVIDERS } from 'angular2-apollo';
/* ... */
bootstrap(App, [ APOLLO_PROVIDERS ]);
```

If so, are you using `@Apollo` decorator or `Angular2Apollo` service?

**Comment by TrikinCurt** [comment]
It works if I build angular2-apollo from the source - is the npm out of date?

**Comment by kamilkisiela** [comment]
@TrikinCurt Yes, there were few PRs accepted but the new version hasn't been released yet.

I think you should expect new release in few days!

**Comment by kamilkisiela** [comment]
@TrikinCurt You can update your app to use the latest release of `angular2-apollo`, which is `0.3.0`.

Let me know if it works for you!

**Comment by kamilkisiela** [comment]
@mention me if it is still an issue
