### ISSUE TITLE
No way to get loading state of a query

### ISSUE THREAD

**Issue by stubailo** [apollostack/angular2-apollo#36]
In `react-apollo`, loading state of a query is extracted from the Redux store directly (I think - is this correct @jbaxleyiii?). This approach probably won't work with Angular 2.

So how can we make it accessible? Should we add an API to `ApolloClient` for this? Perhaps it should be in the results returned by the `watchQuery` observable?

**Comment by purban** [comment]
If the watchQuery could have a method to fetch the loading state that would be perfect. 👍

**Comment by kamilkisiela** [comment]
With decorator, for now we have just `loading: boolean` that is set to `true` when subscription begins and to `false` when data is ready or there was an error.

https://github.com/apollostack/angular2-apollo/blob/master/src/apolloDecorator.ts#L154-L162

**Comment by stubailo** [comment]
Related: https://github.com/apollostack/apollo-client/issues/342

**Comment by kamilkisiela** [comment]
#43
