### ISSUE TITLE
The decorators are using the client but it's not injected

### ISSUE THREAD

**Issue by purban** [apollostack/angular2-apollo#37]
The client is an arg of the decorator but the anotation is outside the class, so the only way to use it is by actually importing the client. In Angular2 we do DI through the constructor of the app, so it would make more sense to have the annotation inside any of the class' member.

https://github.com/apollostack/angular2-apollo/blob/master/tests/apolloDecorator/queries.ts#L378

Unfortunately right now I don't have any suggestion to solve this, but at least it will be tracked.

**Comment by kamilkisiela** [comment]
#22 and #26

**Comment by kamilkisiela** [comment]
Closing in favor of #41
