### ISSUE TITLE
Can't call rxjs observable operators on object returned by watchQuery

### ISSUE THREAD

**Issue by superchris** [apollostack/angular2-apollo#48]
Tried to write some code that did something like:

```
apolloClient.watchQuery(someQuery).map( (data) => data.stuff)
```

and was surprised to find map wasn't available even after I remembered to do the right rxjs import. It seems like this is something that would be desirable, but watchQuery doesn't return a real rxjs observable AFAICT. Am I doing it wrong or is this just not a thing? I can try to do a PR if this is something that's just not there yet.

**Comment by Urigo** [comment]
@superchris can you try with the latest master?

If it doesn't work for you, I would love a PR for that and would happily merge!

**Comment by Urigo** [comment]
Try the new 0.4.0 version

**Comment by kamilkisiela** [comment]
@superchris Currently `Angular2Apollo.watchQuery` returns a simple Observable ([`ObserableQuery`](https://github.com/apollostack/apollo-client/blob/master/src/ObservableQuery.ts#L11)).

You can use it with Rx Observable:

```ts
import {
  Observable,
} from 'rxjs/Observable';

import 'rxjs/add/observable/from';

class App {
  ngOnInit() {
    const origin = this.angular2Apollo.watchQuery(options);
    const obs = Observable.from(origin);

   origin.refetch() // available
   obs.refetch() // not available
  }
}
```

I'll try to solve this, feel free to help with it :)

**Comment by kamilkisiela** [comment]
@superchris With `v0.4.2` you'll be able to use Rx Operators with Observable returned by `watchQuery` method. 

PR #59 

Should be released soon.
