### ISSUE TITLE
Correct usage with RxJS

### ISSUE THREAD

**Issue by patrickkeller** [apollostack/angular2-apollo#56]
According to the docs the `watchQuery` should return an Observable that can be used with RxJS. But if i try to subscribe to the `ApolloQueryObservable` i get `Cannot read property subscribe of undefined`. This happens because the `ApolloQueryObservable` has not such method.

I figured out that the following works:

```js
    this.users = angularApollo.watchQuery({
      query: gql`
        query {
          users {
            username
            name
          }
        }
      `
    }).apollo;

    this.users.subscribe({
      next: ({data}) => {
        console.log(data);
      },
      error: (err) => {
        console.log(err);
      }
    });
```

But this won't work:

```js
    this.users = angularApollo.watchQuery({
      query: gql`
        query {
          users {
            username
            name
          }
        }
      `
    });

    this.users.subscribe((user) => {
      console.log(user);
    });
```

How is this intended to work? Maybe i'm getting something wrong...

**Comment by kamilkisiela** [comment]
@patrickkeller #59 should fix it but could you check it in your app?
