### ISSUE TITLE
Bug with watchQuery / ApolloQueryObservable

### ISSUE THREAD

**Issue by DxCx** [apollostack/angular2-apollo#76]
Hi, I Would like to report a bug i've just found in the Observable,
looking at ApolloQueryObservable (https://github.com/apollostack/angular2-apollo/blob/b887d17b6ef0a74fcfed1853ca8c9921fc706162/src/ApolloQueryObservable.ts#L9),
it is inherenting from Observable, and getting the observer creation cb as last parameter,
next, looking at watchQuery function (https://github.com/apollostack/angular2-apollo/blob/master/src/Angular2Apollo.ts#L26),
if there is no variables object next to the query, undefined will be passed there (https://github.com/apollostack/angular2-apollo/blob/master/src/Angular2Apollo.ts#L46)
So basiclly, we have a new observable that will call undefined upon subscription.

from what it looks like on variables flow, it looks like the intention is to use the watchQuery Observable (from apollo-client) in case variables are not used.

-----

Also, i noted the observable doesn't send any values,
do i need to make any special implementation on the server side (Regular query is working)?

**Comment by DxCx** [comment]
small update, 
since i'm not using variables (ATM) just trying to figure out if the basic flows are working,
i tried to access client.watchQuery directly (which more or less confirms my assumption above),
now the watchQuery sends me initial value, but i don't see any polling or updating happens. :\

**Comment by DxCx** [comment]
Hi,

I've submitted a patch that fixes the issue i reported,
also, using forceFetch: true, pollInterval: 1 i was able to make it reactive (Altought it doesn't seem good solution performance-wise).
so now i'm only left with the question, do i need to do any special implementation on server side?
(Now i return different timer string every second)

**Comment by kamilkisiela** [comment]
It's been fixed in #72 .

Some time ago we moved RxJS related logic to separate package `apollo-client-rxjs`.

**Comment by DxCx** [comment]
Cool, great :)
Did you make sure the unit test will test this flow?

**Comment by kamilkisiela** [comment]
Yes yes yes :)

You can [take a look](https://github.com/kamilkisiela/apollo-client-rxjs/blob/master/tests/rxify.ts#L23-L53)

**Comment by DxCx** [comment]
Yep, great, will cancel my PR :)
