### ISSUE TITLE
Hello World: casual-browserify fails in Windows

### ISSUE THREAD

**Issue by robertohuertasm** [apollostack/angular2-apollo#83]
I've been trying to run the example in Windows and I've had to change several things to make it work. I'm going to raise some issues in order to know if there's something that I'm missing or the repo has to be updated.

First problem that I have found is that casual-browserify seems to fail in Windows. [I've submitted a PR](https://github.com/Klowner/casual-browserify/pull/2) in order to solve it.

**Comment by kamilkisiela** [comment]
Could you try to use `casual` instead of `casual-browserify`? It would help a lot, maybe we could just switch to `causal` and that's it :)

**Comment by robertohuertasm** [comment]
Sure, I'll give it a try and let you know!

**Comment by kamilkisiela** [comment]
@robertohuertasm Hi again! :) Could you try the new example #88 ?

**Comment by robertohuertasm** [comment]
Ok. Btw, I've tried `casual` and seems to be working

**Comment by kamilkisiela** [comment]
That's fantastic! I'll merge it soon

**Comment by kamilkisiela** [comment]
@robertohuertasm I really appreciate your feedback! Thank you so much :)

**Comment by robertohuertasm** [comment]
@kamilkisiela you're very welcome! :wink: It's a pleasure to help in any way possible. I'm testing it right now. It takes forever to install all the npm dependencies... Server works ok but the client is not working for me. It's complaining of lacking typings (see the attachment). I'd suggest adding some postInstall script in order to execute typings install too because I was lacking graphql typings too (this one is defined in typings.json).
![errors](https://cloud.githubusercontent.com/assets/696981/18257698/4499e8b0-73c8-11e6-9a12-09a889992046.PNG)

**Comment by robertohuertasm** [comment]
Which typescript version should I be using? I've got 1.8.10 installed.

**Comment by kamilkisiela** [comment]
But the `typings/` suppose to be included in the repository right now, so there's no point of use `postinstall` for it.

AngularCLI uses ts@2.0.0

Try to run this:
```
npm uninstall -D typescript
npm i -D typescript@beta
```

**Comment by robertohuertasm** [comment]
@kamilkisiela yes, that did the trick!
