### ISSUE TITLE
Hello World: apollo-server module has been moved

### ISSUE THREAD

**Issue by robertohuertasm** [apollostack/angular2-apollo#85]
In order to make the example work I've had to install `apollo-server package` and import `apolloExpress` from there and not `apolloServer` from `graphql-tools` as in the current code. If I didn't do this I would get some error stating that the apollo-server had been moved.

**Comment by kamilkisiela** [comment]
As I mentioned in other issue that you posted, I will move Hello World to angular-cli and with that I will use `apollo-server@0.2.X`.

It's already in use in GitHunt-Angular2

**Comment by kamilkisiela** [comment]
Related #88
