### ISSUE TITLE
Hello World: schema needs to be of type GraphQLSchema

### ISSUE THREAD

**Issue by robertohuertasm** [apollostack/angular2-apollo#86]
See #83, #84 and #85.

According to this changes I've got a new error stating that the schema had to be of type GraphQLSchema so I've changed the string into a valid GraphQL schema.

Note: I was tempted to do a PR with all this but I wasn't fully sure that this was a problem with the repo as I was under the impression that maybe there's something that I'm missing. Anyway, if you feel that a PR would be nice I would not have any problem with that.

**Comment by kamilkisiela** [comment]
New version of Hello World is coming soon #88
