### ISSUE TITLE
Hello World: Error on app.component.ts ngOnInit

### ISSUE THREAD

**Issue by robertohuertasm** [apollostack/angular2-apollo#87]
Related to #83, #84, #85 and #86.

I was getting the following error:
```
Type 'Observable<any>' is not assignable to type 'ApolloQueryObservable<any>'
```

I've had to cast the return of the map function in line 44 to `ApolloQueryObservable<any>`.

```
}).map(result => result.data.users) as ApolloQueryObservable<any>;
```

**Comment by kamilkisiela** [comment]
This is because `.map` returns an `Observable` but it's still `ApolloQueryObservable`. We will try to solve this some way but I don't think it's possible right now.

I added `as` thing in #88
